### ISSUE TITLE
Electron-Vue下Import报错

### ISSUE THREAD

**Issue by dtboy1995** [OrangeXC/vue-coverflow#29]
### 环境
```
 Electron: 6.1.12
 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 20.22 GB / 31.91 GB
  Binaries:
    Node: 12.14.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD
```

### 报错
```log
\node_modules\vue-coverflow\lib\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import coverflow from './Coverflow.vue'
                                                                                                                                                           ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Module._compile (internal/modules/cjs/loader.js:883:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

### Code
```js
import coverflow from "vue-coverflow";
```

**Comment by dtboy1995** [comment]
### 追加错误 从项目拷贝出来后，可以import后
```log
vue.esm.js?a026:628 [Vue warn]: Error in directive coverflow bind hook: "TypeError: Cannot read property 'style' of undefined"

found in

---> <Coverflow> at src/renderer/views/dashboard/coverflow/Coverflow.vue
       <Index> at src/renderer/views/dashboard/index.vue
         <AppMain> at src/renderer/views/layout/components/AppMain.vue
           <Layout> at src/renderer/views/layout/Layout.vue
             <App> at src/renderer/App.vue
               <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
callHook$1 @ vue.esm.js?a026:6693
_update @ vue.esm.js?a026:6612
updateDirectives @ vue.esm.js?a026:6593
invokeCreateHooks @ vue.esm.js?a026:6080
createElm @ vue.esm.js?a026:5967
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
merged @ vue.esm.js?a026:3310
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
createChildren @ vue.esm.js?a026:6064
createElm @ vue.esm.js?a026:5965
patch @ vue.esm.js?a026:6488
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
init @ vue.esm.js?a026:3127
merged @ vue.esm.js?a026:3310
createComponent @ vue.esm.js?a026:5989
createElm @ vue.esm.js?a026:5936
updateChildren @ vue.esm.js?a026:6227
patchVnode @ vue.esm.js?a026:6330
patch @ vue.esm.js?a026:6493
Vue._update @ vue.esm.js?a026:3957
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
run @ vue.esm.js?a026:4563
flushSchedulerQueue @ vue.esm.js?a026:4319
eval @ vue.esm.js?a026:1989
flushCallbacks @ vue.esm.js?a026:1915
Promise.then (async)
timerFunc @ vue.esm.js?a026:1942
nextTick @ vue.esm.js?a026:1999
queueWatcher @ vue.esm.js?a026:4411
update @ vue.esm.js?a026:4553
notify @ vue.esm.js?a026:739
reactiveSetter @ vue.esm.js?a026:1064
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2797
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2796
updateRoute @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2225
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2088
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2210
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1894
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1901
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1901
runQueue @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1905
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2205
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1894
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1898
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2190
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1937
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2013
Promise.then (async)
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1960
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1981
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1981
flatMapComponents @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1980
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1916
iterator @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2171
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1897
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1901
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1901
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1898
(anonymous) @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2190
eval @ permission.js?5048:7
iterator @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2171
step @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1897
runQueue @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1905
confirmTransition @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2198
transitionTo @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2085
init @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:2788
beforeCreate @ D:\hou\ar-desktop\node_modules\vue-router\dist\vue-router.common.js:1244
invokeWithErrorHandling @ vue.esm.js?a026:1863
callHook @ vue.esm.js?a026:4228
Vue._init @ vue.esm.js?a026:5013
Vue @ vue.esm.js?a026:5094
eval @ main.js?cebd:18
./src/renderer/main.js @ renderer.js:4892
__webpack_require__ @ renderer.js:834
fn @ renderer.js:131
1 @ renderer.js:5241
__webpack_require__ @ renderer.js:834
(anonymous) @ renderer.js:972
(anonymous) @ renderer.js:975
Show 56 more frames
vue.esm.js?a026:1897 TypeError: Cannot read property 'style' of undefined
    at displayIndex (coverflow.js?47a9:12)
    at bind (coverflow.js?47a9:118)
    at callHook$1 (vue.esm.js?a026:6691)
    at _update (vue.esm.js?a026:6612)
    at Array.updateDirectives (vue.esm.js?a026:6593)
    at invokeCreateHooks (vue.esm.js?a026:6080)
    at createElm (vue.esm.js?a026:5967)
    at VueComponent.patch [as __patch__] (vue.esm.js?a026:6488)
    at VueComponent.Vue._update (vue.esm.js?a026:3954)
    at VueComponent.updateComponent (vue.esm.js?a026:4075)
```
